docs/sources/writing-guide/_index.md
As a contributor who has read the guidelines and writes frequently, I want to access the templates quickly so I can start writing. Alternatively, I could bookmark the GitHub location instead of the guide. However, I want to keep _Writers’ Toolkit_ as my source of overall truth and would prefer to remember only that I need to go there for access to information quickly.
=> Reduce number of clicks to templates.

docs/sources/writing-guide/front-matter/index.md
The main goal of this PR is to recommend against using special characters in front matter, as decided in this [slack chat](https://raintank-corp.slack.com/archives/C01EK60DKC5/p1672934684107869).
As I edited, I noticed some of the Alias pages were under their own `h2` , so I also moved them. To avoid an `h4`, I used description lists. The presentation should look something like this (not sure about in the new docs style):
=> Frontmatter; Prescribe against special characters

docs/sources/writing-guide/front-matter/index.md, docs/sources/writing-guide/markdown-guide/index.md
- https://github.com/grafana/writers-toolkit/commit/d3d3b9588e29f93939ea8f280838f3ceac32f585 fixes #167.  It uses a definition list, which renders as follows on my local build:
Until the docker image updates I can't see how it looks in new styling, but I checked the formatting on another hugo site and it was fine.
I didn't change the content, but I think that's out of scope for this issue.
- https://github.com/grafana/writers-toolkit/commit/fc4614df5d03053fc47538dd43b6506fcf2bd2b4 sets off a sentence with comma and relative clause. The original as an an unrestricted phrase sounded off to my ear. It's not very important in the scheme of things but it's important to me @osg-grafana :pray: :pray:
=> Fix frontmatter table and use comma for restrictive modifier

docs/sources/writing-guide/markdown-guide/index.md
We don't come right out and say anywhere that we're using Hugo (we assume you know, we should actually say we use it).
Also adding links to:
Hugo web site
CommonMark specification
CommonMark quick reference
=> Add links to Markdown references.

docs/sources/style-guide/ux-writing/index.md
When phrases and sentences are grammatically complete before lists, they are easier to translate.
=> Grammatically complete phrase or sentence before punctuation

docs/sources/writing-guide/front-matter/index.md
This PR adds information about the `draft: true` option to prevent a draft document from being published on the website.
=> Add draft true to frontmatter/index.md

docs/sources/_index.md
Check with `$ make docs`, browse to http://localhost:3002/docs/writers-toolkit and confirm that the "Open source" label is present before the title.
=> Add OSS product label to all Writers' Toolkit pages

docs/sources/writing-guide/contribute-documentation/index.md
Documenting the recommendation to use GitHub keywords to automatically close related issues when PRs merge.
Also added link to longer backporting topic elsewhere in the guide.
=> Add GitHub keywords to PR section.

docs/sources/writing-guide/front-matter/index.md
I think it's useful to know that one of the things that the docs-validator linter checks if if topic headings match the title listed in the metadata, so I'm adding it to the Writer's Toolkit.
=> Add linter validation to metadata page.

docs/sources/writing-guide/front-matter/index.md
Readers should understand the origin of cascading labels and how to override them for single pages or whole directories.
=> Add labels front matter documentation

docs/sources/_index.md, docs/sources/style-guide/_index.md, docs/sources/style-guide/capitalization-punctuation/index.md, docs/sources/style-guide/inclusive-writing/index.md, docs/sources/style-guide/style-conventions/index.md, docs/sources/style-guide/ux-writing/index.md, docs/sources/style-guide/voice-tone-guidelines/index.md, docs/sources/style-guide/write-for-developers/index.md, docs/sources/writing-guide/_index.md, docs/sources/writing-guide/about-grafana-docs/index.md, docs/sources/writing-guide/contribute-documentation/index.md, docs/sources/writing-guide/contribute-release-notes/index.md, docs/sources/writing-guide/documentation-structure/index.md, docs/sources/writing-guide/front-matter/index.md, docs/sources/writing-guide/image-guidelines/index.md, docs/sources/writing-guide/markdown-guide/index.md, docs/sources/writing-guide/references/index.md, docs/sources/writing-guide/shortcodes/index.md, docs/sources/writing-guide/tooling-and-workflows/_index.md, docs/sources/writing-guide/tooling-and-workflows/backporting/index.md, docs/sources/writing-guide/topic-types/_index.md, docs/sources/writing-guide/topic-types/concept/index.md, docs/sources/writing-guide/topic-types/reference/index.md, docs/sources/writing-guide/topic-types/task/index.md, docs/sources/writing-guide/topic-types/tutorial/index.md, docs/sources/writing-guide/useful-link-text/index.md
See individual commits. 
Updated documentation is in [4eaf204](https://github.com/grafana/writers-toolkit/pull/226/commits/4eaf204ac203aa2fcf2fd06013b2b01f3c07e9e5).
Closes [4eaf204](https://github.com/grafana/writers-toolkit/pull/226/commits/4eaf204ac203aa2fcf2fd06013b2b01f3c07e9e5).
=> Document why relative aliases are used in versioned documentation

.gitignore, docs/docs.mk, docs/make-docs
CI typically invokes `make -B` because git doesn't store timestamps. This results in changes to the working tree when invoking `make docs` if the version of `docs.mk` committed to the repo is different to one in Writers' Toolkit. Some CI tests use the exit status of `git diff` to determine if generated files have been committed and this working tree change interferes.
This PR does not remove the original source file `scripts/make-docs` because that would break existing workflows.
Once this PR has been merged and rolled out, that script can be removed.
=> Use PHONY update target to avoid causing diffs in CI

docs/sources/style-guide/style-conventions/index.md, docs/sources/writing-guide/shortcodes/index.md
- Documents the `admonition` shortcode, fixes #231
- Removes the `tips` admonition, fixes #233 
- Standardizes shortcode document so shortcode names render in `code` element in headings
=> Feat: document shortcode for admonitions

docs/sources/writing-guide/front-matter/index.md
- Update cascading front matter documentation to explain the two forms
- Fix heading hierarchy and emphasize advice with note admonition
- Document date front matter parameter
=> Document date parameter

docs/sources/writing-guide/markdown-guide/index.md, docs/sources/writing-guide/shortcodes/index.md
Add clarifying text for when to use markdown vs a shortcode for adding images in docs
=> docs: clarify markdown vs shortcode use cases for images

docs/sources/writing-guide/shortcodes/index.md
This PR adds a simple example of a section short code with the page descriptions.
=> Add simple example for descriptions

docs/sources/writing-guide/references/index.md
Updated the cross-repository link example and the references page.
=> Add example for cross-repo links

.github/workflows/test.yml
- Structured output for use with [`reviewdog`](https://github.com/reviewdog/reviewdog). You can achieve the original error output by piping the output to the following `jq` expression: `jq -r '"ERROR: \(.location.path):\(.location.range.start.line):\(.location.range.start.column): \(.message)"'`.
- Suggestions for simple link fixes. In GitHub, [`reviewdog`](https://github.com/reviewdog/reviewdog) comments these suggestions for convenient replacement.
- Support for anchors referring to repeated headings. In the case that a page has multiple headings that share the same text, the renderer appends a zero indexed, numbered suffix to the identifier. For example, when there are two headings that are both "Heading text", the first anchor identifier is `heading-text` and the second is …
=> Use doc-validator v3.0.0

docs/sources/writing-guide/references/index.md
The Writer's Toolkit page for [links and cross-references](https://grafana.com/docs/writers-toolkit/writing-guide/references/#understanding-hyperlinks) has a bare URL in the first example:
`For example, https://github.com.`
But all the rest of our link guidance suggests that we do not publish bare URLs, but provide link text.  The Style Guide [section on links](https://grafana.com/docs/writers-toolkit/style-guide/style-conventions/#links-and-references) implies that there should be link text.  As does the [Write useful link text ](https://grafana.com/docs/writers-toolkit/writing-guide/useful-link-text/)topic
`For example, [GitHub](https://github.com]`
=> Updating the example link format from a bare link to a link with link text.

docs/sources/writing-guide/references/index.md
This PR corrects slashes in an example on references/index.md that used \instead of /.
=> [References] Fixed incorrect slashes in link example

docs/sources/style-guide/ux-writing/index.md
We discussed "modals" in the Style Council meeting this week.
Adding a note to the style guide to clarify not to use the term in documentation.
=> Add note to modals.

docs/sources/writing-guide/shortcodes/index.md, docs/sources/writing-guide/tooling-and-workflows/run-a-local-webserver/index.md
Adds a make doc example covering when the project directory doesn't match the standard project.
=> Add make doc example

docs/sources/write/style-guide/ux-writing/index.md
Changes:
- Use `<br>` instead of `<p></p>` which weren't having the intended effect
- Use Markdown in quotes instead of HTML 
- Format quotes over multiple lines
- Add example for button sentence case.
- Spelling
=> Updates to the UX writing style guide

docs/sources/write/shortcodes/index.md
This PR replaces PRs #264 and #271. Starting a new PR because of major structural changes to the Writer's Toolkit since the branches for those original PRs were cut.
***
For context on the need, refer to [2023-04 Flexible linking -- Problem](https://docs.google.com/document/d/1F9aiHhyruW0d_zMoL5yjG37Qo-OZ--x4Ivx2Hdu1cYs/edit#heading=h.xxn36c2bhtyg) and [2023-04 Flexible linking -- Consensus](https://docs.google.com/document/d/1F9aiHhyruW0d_zMoL5yjG37Qo-OZ--x4Ivx2Hdu1cYs/edit#heading=h.ve4du26wqsib).
I'd like to use this documentation to drive the implementation.
The documentation should help a user use this shortcode with confidence, if anything is unclear or you believe it is overly complicated, please add comments to this PR and I will incorporate the feedback in both the documentation …
=> docs: add `docs/reference` shortcode guidance

docs/sources/write/image-guidelines/index.md
I found a missing closing parenthesis, but ended up making some changes so it follows our Vale rules.
=> Vale fixes to image guidelines page

docs/make-docs
Now the repository is called `beyla` which matches the project name. Previously it was `ebpf-autoinstrument`.
=> Update beyla source to reflect the new repository name

docs/sources/write/style-guide/style-conventions/index.md
The example text from the `warning` admonition section was copied from the `caution` section.
=> Fix warning admonition example text

.vale.ini, vale/.vale.ini, vale/.vale.jsonnet, vale/Makefile
@moxious
> In an audit of 63 instances where this vale rule triggered on grafana/grafana, the 30+ I looked at were all incorrect / in contexts that I think ought not have been flagged.
Co-authored-by: David Allen <david.allen@grafana.com>
=> Generate Vale configuration from common source and disable GoogleUnits rule

.vale.ini, vale/.vale.ini, vale/.vale.jsonnet, vale/Makefile
Means that writers no longer have to worry about spell checking in bold text which is used in our style to represent UI elements which are frequently spelled using non dictionary words.
To test, checkout this branch in VSCode configured with Vale and typo something in bold text like the following:
```markdown
_Seplling mistkae_
`Seplling mistkae`
**Seplling mistkae**
```
Note that Vale style applies rules to italic emphasis.
=> Ignore the inline token representing bold emphasis

docs/sources/review/lint-prose/index.md
Adding steps to install and configure Vale for VSCode. This will enable Vale linting on the current topic open in VSCode. Vale linting is done at each save. The Vale output is shown in the PROBLEMS tab in VSCode.
=> Add Vale in VSCode steps

docs/sources/write/reuse-content/reuse-shared-content/index.md
When I'm using the directions on the [Reuse shared content](https://grafana.com/docs/writers-toolkit/write/reuse-content/reuse-shared-content/) page, I'm almost always adding a single file in an existing `shared` directory, not adding the directory. As a result, I'm always looking for the spot where those directions begin, halfway through the steps. This PR adds sub-headings to the page to delineate the creation of the directory from the creation of the file.
=> Add sub-headings to shared content page

docs/sources/review/lint-prose/index.md
Adds an Errata section for the Vale linter and adds a specific section to explain the "allows to" rule.
For some reason, when I build this locally, the right sidebar renders at the bottom of the page, but it's also doing this on the original PR.
=> Add "allows to" rule explainer

docs/sources/write/shortcodes/index.md
=> Remove indent from code block inner to make it copy-pastable and add note about `prettier`

docs/sources/contribute-documentation/_index.md
Closes https://github.com/grafana/writers-toolkit/issues/243.
=> Add note that the website repository is private

docs/sources/review/doc-validator/errata.md, docs/sources/write/references/index.md
As long as you don't need contextual linking and you are not linking within your current documentation set, fully qualified URLs are perfectly fine to be used because Hugo will now trim the hostname and scheme away, essentially making them behave like partial URLs with an absolute path.
**Note to reviewers:**
You should primarily worry about reviewing the [references page](https://github.com/grafana/writers-toolkit/pull/322/files#diff-30bddbfa43325a0f94be46d4928423d93981a290cb9aaa0cbd748005c6561d3b).
The `errata.md` changes are generated. Of course, all reviews all also welcome there.
Depends on the implementation in https://github.com/grafana/website/pull/15472.
=> Update linking documentation to reflect that fully qualified grafana.com URLs are no longer discouraged

docs/sources/review/lint-prose/index.md
Add Windows steps to Vale in VS Code instructions on Writer's Toolkit
=> Add Windows steps to Vale in VS Code instructions

docs/sources/write/style-guide/write-for-developers/index.md
The example demonstrated Markdown used in a code block which wouldn't be rendered as the example intended.
The preferred Markdown syntax for italic emphasis is `_` when using `prettier` so I've updated the instructions to use that instead of `*`.
I've also fixed the name of the characters to match their unicode naming and added examples of each of them in case the name is not obvious to readers
=> Fix instructions for placeholder variables

docs/sources/write/shortcodes/index.md
Adds option/guidance for adding a `featureFlag` parameter/argument for the public-preview shortcode
Do not attempt to merge until the actual work on the website has been done. Raised on [issue 15642](https://github.com/grafana/website/issues/15642)
=> Add optional featureFlag parameter for public-preview shortcode

docs/sources/write/front-matter/index.md, docs/sources/write/markdown-guide/index.md, docs/sources/write/references/index.md, docs/sources/write/reuse-content/reuse-shared-content/index.md, docs/sources/write/shortcodes/index.md
On the [shortcode](https://grafana.com/docs/writers-toolkit/write/shortcodes/) and [front matter](https://grafana.com/docs/writers-toolkit/write/front-matter/) pages, the code font in the headings reduces the amount of white space there is between sections and makes the pages hard to scan. Propose taking things out of code font and just capitalizing them since the examples indicate how they should be written/formatted.
=> Make headings plain text

docs/sources/write/shortcodes/index.md
Because of the `pre` tags (`` ` ``), the encoded string is being interpreted literally.
Thankfully we can just use the actual HTML comment text and it works as expected.
To test, run `make docs` locally and browse to http://localhost:3002/docs/writers-toolkit/write/shortcodes/#code.
=> Fix formatting of `prettier` lint ignore comment

docs/sources/write/shortcodes/index.md
Constrains use cases for the `collapse` shortcode to deprecations and configuration options per the Oct 5 style roundtable meeting. Also adds guidance re lead-in sentences and titles.
=> Add collapse shortcode use cases

docs/sources/write/image-guidelines/index.md
Add guidance about alt text and figure captions.
=> [WIP] Add information about alt text

docs/sources/review/run-a-local-webserver/index.md
Closes https://github.com/grafana/technical-documentation/issues/735
=> Document that running `make docs` from the root of a repository produces different behavior

docs/sources/write/shortcodes/index.md
This section confused the behavior of the `docs/reference` shortcode and the generic Markdown reference-style link syntax.
=> Fix erroneous documentation

vale/dictionaries/en_US-grafana.dic, vale/dictionaries/wordlist
- [ESLint](https://eslint.org/)
- [Webpack](https://webpack.js.org/)
Note that Webpack is stylized as "webpack" in their own documentation but Wikipedia uses "Webpack" -- https://en.wikipedia.org/wiki/Webpack#:~:text=Node.js%20is%20required%20to%20use%20Webpack.
Related to https://github.com/grafana/plugin-tools/pull/484.
=> Add ESLint and Webpack to dictionary

docs/sources/write/style-guide/word-list/index.md, vale/Grafana/WordList.yml
- **data source plugin**: Consistent with our advice to eliminate "datasource" (one word).
- **data-source plugin**: Technically correct as "data source" becomes the adjective.
Pragmatically, requires a lot of education and changes across all existing documentation and also across the Grafana UI.
> In the end, with Eve and Fiona considering all angles, the decision was not to add the hyphen.
Style roundtable discussion: https://docs.google.com/document/d/1uCjtHEy0lpZggkpgsLDjWwxV9K6h7vcsG2dy4TOS6EA/edit#heading=h.kr6qvkov3k9p.
=> Use "data source plugin" instead of "data-source plugin"

vale/Google/WordList.yml, vale/dictionaries/en_US-grafana.dic, vale/dictionaries/wordlist
Per @GrafanaWriter, use _disaggregate_ as the antonym of _aggregate_; for example, "disaggregated metrics that have been previously aggregated"
cc @noise, @nickfuzer, @09jvilla, @colega
=> Docs: Add disaggregate to Vale linter list of words

update-make-docs/action.yml
- Add action for updating the `make docs` procedure
- Add shell
- Add name and comments explaining behavior and support existing branches
- Fix PR_OPTIONS environment variable
- Add command traces
- Ensure PR is created if it can be
- Correctly set GH_TOKEN
- Refactor script to clarify logic
- Avoid use of `--fill` that doesn't play nice with partial fetches
- Fix open PR checkout
=> Add 'Update `make docs` procedure' action

docs/sources/about-grafana-docs/index.md
Add k6-docs to the list on "Introduction to documentation", now that we have migrated the docs to Grafana. :)
=> Add k6-docs to list of project repositories

docs/sources/contribute-documentation/contribute-release-notes/index.md, vale/Grafana/Headings.yml
My first pass at a What's new update. Not sure about the content I commented out, I think I remember making an informed decision to delete the info, but I'd like another set of eyes on it. I feel like I still need to leave some information about the workflow involved in pulling cloud rel notes into OSS. 
TBD:
=> What's new contribution guidelines update 

docs/sources/write/style-guide/style-conventions/index.md
This PR changes the gerund used in the heading `Sorting lists` to a simple verb `Sort lists`.
=> Simplify verb in heading

docs/sources/write/front-matter/index.md
- Update advice to say that you must add an alias when a page is move.
- Update advice to say that you should add a comment explaining relative aliases.
- Visually restructure examples for improved readability.
=> Update aliases documentation with 'Brunch and learn' feedback

docs/sources/write/shortcodes/index.md
=> Docs: Add a tip admonition.

docs/sources/write/front-matter/index.md
- Fix bad example
- Emphasize that the current directory is the directory containing the page, not the directory of the page
- Use more easily understood terminology in table demonstration
=> Fix aliases documentation and incorporate more feedback from 'Brunch and learn' session on the topic

docs/sources/write/shortcodes/index.md
The note about reference links not working within admonition shortcodes isn't accurate. 
Reference links don't work in admonitions if you are using references defined at the topic level (outside the admonition)
Reference links do work if you define the links within the admonition.
Example. The following admonition uses inline link definitions.
```
{{% admonition type="note" %}}
The Grafana shortcode templates are defined in the `layouts/shortcodes` folder of the website repository which is only accessible to Grafana Labs employees.
To request custom shortcodes, [create an issue](https://github.com/grafana/writers-toolkit/issues).
{{% /admonition %}}
```
This admonition will also render properly if you define reference links within the admonition.
```
{{% admonition type="note" %}}
The …
```
=> Clarification about ref links in admonitions

docs/sources/write/front-matter/index.md, docs/sources/write/shortcodes/index.md
This PR adds `cascade` and `param` info to Front Matter and shortcodes topics in the Writer's Toolkit
=> Add cascade and param info to Front Matter and Shortcodes topics

.gitignore, docs/sources/contribute-documentation/contribute-release-notes/index.md
While creating an entry for What's new on cloud I found a couple of discrepancies in the related [help page](https://grafana.com/docs/writers-toolkit/contribute-documentation/contribute-release-notes/).
=> Contribute to What's new page: Correct and add some information

docs/sources/write/deprecate-remove/_index.md
- Avoid first person.
- Avoid passive voice where appropriate.
- Avoid unicode quotes.
- Use placeholder text style from style guide.
- Use semantic line breaks for better GitHub UI diffs.
- Prefer "documentation" over "docs".
=> Lint deprecation guidelines for Vale warnings

docs/sources/write/style-guide/write-for-developers/index.md
I'm starting to revise the documentation for formatting code examples and add an additional section for specifically handling partial code examples.
It turns out it's super hard!
I'd love any ideas on how we can better explain how to use snippets.
Is the increased verbosity avoidable or is it necessary to deal with complicated integration?
=> Document partial code examples

docs/sources/write/links/index.md
Also make clear that links can be to either versioned or unversioned documentation.
=> Note that `doc-validator` does not check full URL links

docs/sources/write/style-guide/word-list/index.md, docs/variables.mk, vale/Grafana/DialogBox.yml, vale/Grafana/WordList.yml
- Match 'dialog' only if it is not proceeded by ' box'.
- Link directly to the Grafana documentation heading for further information because it deviates from Google style.
- Explain the reason for the deviation.
=> Fix Vale rules for use of 'dialog box'

docs/sources/write/markdown-guide/index.md, vale/Grafana/GoogleParens.yml, vale/Grafana/Parentheses.yml, vale/google.jsonnet
This also removes the guidance to avoid "single-child headings" because I can't find any justification for it online.
Closes https://github.com/grafana/writers-toolkit/issues/196
=> Lint Markdown guide 

docs/sources/write/front-matter/index.md
Closes https://github.com/grafana/writers-toolkit/issues/391.
=> Document `slug` front matter

docs/sources/write/front-matter/index.md, docs/sources/write/style-guide/write-for-developers/index.md
Closes https://github.com/grafana/writers-toolkit/issues/286
The deletions come from [596217b](https://github.com/grafana/writers-toolkit/pull/448/commits/596217bf8dfebf53fc68d81d8900bf033fae1380). I'm not sure why that content was where it was and I don't think it is worth incorporating with the rest of the page.
=> Document front matter for tutorials

docs/sources/write/shortcodes/index.md
Implemented in https://github.com/grafana/website/pull/17339/ and refined in https://github.com/grafana/website/pull/18011
=> Document `depth` parameter for the `section` shortcode

docs/sources/write/style-guide/word-list/index.md
Add correct capitalization of Node Exporter to word list. This decision was made in the style roundtable based on how it's referred to in the [Prometheus docs](https://prometheus.io/docs/guides/node-exporter/).
=> Add node exporter to word list

docs/sources/review/lint-prose/index.md, docs/sources/shared/make-help.md, vale/Grafana/Acronyms.yml
- Use preferred product name Visual Studio Code, consistent with its documentation (https://code.visualstudio.com/).
- Update the Vale download URL.
- Use preferred admonition shortcode syntax.
- Use semantic line breaks for better future line based diffing in the GitHub UI.
- Avoid passive voice.
Closes https://github.com/grafana/writers-toolkit/issues/507.
=> Review "Lint prose" page

vale/Grafana/Headings.yml
> Grafana AWS Observability for Grafana Cloud provides you with a single place to gain better visibility into the health and performance of your infrastructure and large scale applications.
> AWS Observability is available immediately with your Grafana Cloud account.
https://grafana.com/docs/grafana-cloud/monitor-infrastructure/aws/
=> Add AWS Observability

vale/dictionaries/en_US-grafana.wordlist
Remove flamegraph. The content team chimed in and decided we should use flame graph as two words. I've reverted the change I made earlier and have also reviewed all of the content in the Cloud Profiles content to make flame graph two words in the documentation. I'll update the Pyroscope OSS content next. 
Part of https://github.com/grafana/pyroscope-squad/issues/123
=> Remove flamegraph in favor of flame graph

vale/dictionaries/en_US-grafana.dic, vale/dictionaries/en_US-grafana.wordlist
Reverts grafana/writers-toolkit#592
Sorry @knylander-grafana, I didn't explain properly in my previous PR. The dictionary uses stem words and affix rules to build the dictionary. In my PR (and now this one), the stem is `profile` and the affix rules are `DGRS`. Each of those affix rules are defined in https://github.com/grafana/writers-toolkit/blob/main/vale/dictionaries/en_US-grafana.aff and they have different behavior and are somewhat mnemonic.
- `D` is the `ed` suffix
- `G` is the `ing` suffix
- `R` is the `er` suffix
- `S` is the plural suffix
Each rule knows how to correctly remove from the stem if needed to apply the suffix.
This lets me add a single stem word `profile` and have the dictionary understand all of:
- profiled
- profiling
- profiler
- profiles
=> Revert "Add profile verb form and affixes"

docs/sources/contribute/release-notes/index.md
Adds guidance for when you need to announce that a previously documented feature has moved into a new release stage.
=> Docs: add guidance for second entries

docs/sources/contribute/release-notes/index.md
Clarified the release notes/what's new to address two things: 
* The What's new process isn't used by all products 
* It's okay to use "we" in the release notes and What's new since they are more conversational tone like blog posts
=> [DOC] Update release notes for second person

vale/dictionaries/en_US-grafana.wordlist
This adds an entry for [Gravatar](https://gravatar.com/), the tool used for populating user avatars in Grafana instances.
=> Adding entry for Gravatar

docs/sources/write/shortcodes/index.md
in a few places, it is written as GRAFANA VERSION which is not correct
=> fixed GRAFANA_VERSION variable

docs/sources/write/tooling-and-workflows/index.md
- Use consistent language when talking about the "default" branch
- Use consistent code blocks (no preceding prompt indicator)
- Use consistent language when talking about command line options.
Options are either long (two dashes) or short (one dash), if an option takes no argument and toggles behavior it is a flag.
- Simplify links to `gh` CLI installation.
- Document how to check out any PR branch (not just one from a fork).
=> Review Tooling and Workflows documentation

vale/Grafana/CHANGELOG.yml, vale/Grafana/README.yml
https://grafana.com/docs/writers-toolkit/write/style-guide/word-list/#changelog
> When naming a file or making a general reference to CHANGELOGs, spell using all caps. When referencing a specific CHANGELOG file, match the same capitalization of that file.
=> Add rule for CHANGELOG

docs/sources/write/style-guide/style-conventions/index.md, vale/Grafana/GoogleOrdinal.yml, vale/Grafana/Ordinal.yml, vale/google.jsonnet
Adds a Numbers section to the style guide. Adds guidance to follow Google style on all number styling except in the case of ordinals.
=> Docs: add ordinal number guidance

vale/Grafana/Quickstart.yml, vale/fixtures/Grafana/Quickstart/.vale.ini, vale/fixtures/Grafana/Quickstart/testinvalid.golden, vale/fixtures/Grafana/Quickstart/testinvalid.md, vale/fixtures/Grafana/Quickstart/testvalid.md
https://grafana.com/docs/writers-toolkit/write/style-guide/word-list/#changelog
> When naming a file or making a general reference to CHANGELOGs, spell using all caps. When referencing a specific CHANGELOG file, match the same capitalization of that file.
Decided in the [2024-03-21 Style roundtable meeting](https://docs.google.com/document/d/1uCjtHEy0lpZggkpgsLDjWwxV9K6h7vcsG2dy4TOS6EA/edit#heading=h.fcyxlafuji70)
=> Add rule for quickstart

vale/Grafana/Ordinal.yml, vale/fixtures/Grafana/Ordinal/.vale.ini, vale/fixtures/Grafana/Ordinal/testinvalid.golden, vale/fixtures/Grafana/Ordinal/testinvalid.md, vale/fixtures/Grafana/Ordinal/testvalid.md
The nonword configuration meant that the token `5th` matches in `75th` for example.
=> Fix Grafana/Ordinal reporting errors on multiple digit ordinals

vale/dictionaries/en_US-grafana.dic, vale/dictionary.jsonnet
Looking at the Google style guide and in the context of technical docs, I think we should include the lowercase boolean to our dictionary: https://developers.google.com/style/word-list#boolean.
=> Add boolean to dictionary.jsonnet

vale/Grafana/Acronyms.yml, vale/Grafana/Archives.yml, vale/Makefile, vale/dictionaries/en_US-grafana.dic, vale/dictionary.jsonnet, vale/fixtures/Grafana/Archives/testvalid.md
False positive spotted in https://github.com/grafana/tempo/pull/3626/files#diff-1e0385ba512bc0e4e0d24fc1695898b9471b5373e1f17120c1c812a60f7980e5R57-R58 
=> Fix false positive for Zipkin product and add OTLP acronym

docs/sources/review/test-documentation-changes/index.md
This PR clarifies the output of running the `make docs` command, and also specifies what's the URL for testing tutorial changes
=> writers toolkit: test docs

docs/sources/_index.md, docs/sources/contribute/_index.md, docs/sources/introduction/index.md, vale/Grafana/DocumentationTeam.yml
[Review home page](https://github.com/grafana/writers-toolkit/commit/b08472eb24b0790e6dbc2cad8860eca3fff3c775) 
Update description to give more context.
Closes #651 
[Review Contribute page](https://github.com/grafana/writers-toolkit/commit/3cfe7e57876833db7dafe3834dc1f96b039a9dfa) 
- Correctly refer to the Grafana Labs documentation team instead of Doc Squad
- Clarify that documentation without a **Suggest an Edit** link is closed source
- Avoid gerund
Closes #652 
[Review Introduction page](https://github.com/grafana/writers-toolkit/commit/c5ec2fa5c4b6d8b4c47fae00fe9513358d9d4737) 
- Update links to some open source projects
- Prefer full URLs
- Prefer Grafana Labs over Grafana
Closes #653 
=> Review some pages

docs/sources/get-started/_index.md
- Prefer 'documentation' over 'docs'
- Link to the 'Documentation structure' page which documents the content framework
- Update link text to match destination page title
- Enclose Slack channel in code formatting
Rest LGTM.
Closes https://github.com/grafana/writers-toolkit/issues/662
=> Review 'Get started with writing documentation' page

docs/sources/shared/make-help.md
- Clarify that website technical documentation lives in `/docs/sources` (EngHub technical documentation lives elsewhere)
- Update `make help` output
Rest LGTM
Closes https://github.com/grafana/writers-toolkit/issues/687
=> Review 'GNU Make help output' shared page

vale/dictionaries/en_US-grafana.dic, vale/dictionary.jsonnet
https://www.google.com/search?q=%22scheduler%27s%22+site%3Akubernetes.io&sca_esv=e8add49ad30124b6&ei=-h1YZrmLBoKmhbIPlvO0uAs&ved=0ahUKEwi58KX74LSGAxUCU0EAHZY5DbcQ4dUDCBA&uact=5&oq=%22scheduler%27s%22+site%3Akubernetes.io&gs_lp=Egxnd3Mtd2l6LXNlcnAiICJzY2hlZHVsZXIncyIgc2l0ZTprdWJlcm5ldGVzLmlvSPYOUIQCWOEMcAF4AJABAJgBM6ABjgGqAQEzuAEDyAEA-AEBmAIAoAIAmAMAiAYBkgcAoAeHAQ&sclient=gws-wiz-serp
https://github.com/grafana/website/pull/19964/files#r1618992079
=> Add scheduler to dictionary with possessive affix rules

vale/Grafana/Shortcodes.yml, vale/fixtures/Grafana/Shortcodes/.vale.ini, vale/fixtures/Grafana/Shortcodes/testinvalid.golden, vale/fixtures/Grafana/Shortcodes/testinvalid.md, vale/fixtures/Grafana/Shortcodes/testvalid.md
In most cases, it isn't needed.
For consistency and pattern matching, we should prefer {{< because it better reflects the shortcode semantics we default to in our minds.
The other syntax is only necessary in specific contexts and the nuances are complicated.
=> Add Vale rule to lint for writing specific shortcodes with percent syntax

vale/dictionaries/en_US-grafana.dic, vale/dictionary.jsonnet
It looks like the docs use [windows_exporter](https://github.com/prometheus-community/windows_exporter) pretty consistently.
=> Add windows_exporter to dictionary

vale/Grafana/Spelling.yml
Bonus, fix the link that was broken. Reported by Beverly.
Will drop [0e81a8a](https://github.com/grafana/writers-toolkit/pull/709/commits/0e81a8a29c4ea161abed7cedb4dd8ad35b0bea3c) before merging which was used to demonstrate the fixed behavior in https://github.com/grafana/writers-toolkit/pull/709#discussion_r1625448068
=> Include word in issue title for spelling false positive 

vale/Grafana/HTTP.yml, vale/fixtures/Grafana/HTTP/.vale.ini, vale/fixtures/Grafana/HTTP/testinvalid.golden, vale/fixtures/Grafana/HTTP/testinvalid.md, vale/fixtures/Grafana/HTTP/testvalid.md
We must use HTTPS to be secure.
=> Add Vale rule to lint for http://grafana.com links

docs/sources/review/lint-prose/dictionary.md, vale/Grafana/DocumentationTeam.yml, vale/dictionary.jsonnet
With reference documentation in place, I think I can start to write specific task documentation for adding different kinds of new words like:
- Add a verb
- Add a product
- Add an acronym
Relates to https://github.com/grafana/writers-toolkit/issues/669
=> Add reference documentation for dictionary template file

docs/sources/review/test-documentation-changes/index.md, docs/sources/shared/make-help.md
Taylor noticed that these instructions cause confusion when they are applied to the website repository.
This change seeks to clarify those slight differences without going too deep because the audience is primarily going to be working in project repositories.
=> Explain differences when working in the website repository

vale/dictionary.jsonnet
This is already used in the [docs](https://grafana.com/docs/grafana-cloud/alerting-and-irm/alerting/set-up/configure-rbac/), but it has come up again as the k6 team is implementing it in Grafana Cloud.
=> Add RBAC to dictionary.jsonnet

docs/sources/write/reuse-content/reuse-shared-content/index.md
- Remove reference to `relref` shortcode. URLs are preferred.
Rest LGTM
Closes https://github.com/grafana/writers-toolkit/issues/760
=> Review "Reuse shared content"

docs/sources/write/markdown-guide/index.md, docs/sources/write/shortcodes/index.md
Duplicate headings only arise when using `docs/shared`.
This PR aims to explain why and how to work around it.
=> Document duplicate heading ids and how to avoid them

docs/sources/write/shortcodes/index.md
Adds documentation entry for the `pyro-flame-graph` shortcode.
Context for the feature is in https://github.com/grafana/website/issues/19745.
=> Document pyro-flame-graph shortcode

docs/sources/review/backport-changes/index.md, docs/sources/write/image-guidelines/index.md, docs/sources/write/style-guide/ux-writing/index.md
`<br>` elements shouldn't be used to present information in most cases. Certainly not to break paragraphs in tables.
Semantic HTML is more accessible, improving readability in screen readers and other tools.
I want to improve this practice across Grafana and we need to lead by example.
https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-br-element 
https://developers.google.com/style/tables#multi-paragraph-table-cells
=> Remove all non-semantic uses of <br>

docs/sources/whats-new.md
The original link goes to a different section that doesn't contain the guidance referenced.
=> Fix link to guidance for dark and light mode

docs/sources/review/lint-prose/rules.md, vale/Grafana/GoogleOxfordComma.yml, vale/google.jsonnet
There are too many false positives and this rule is easier to spot by eye than with regular expressions.
Closes https://github.com/grafana/writers-toolkit/issues/600
=> Demote Grafana.GoogleOxfordComma to suggestion

docs/sources/write/shortcodes/index.md
Add documentation for the `docs/openapi/info` and `docs/openapi/path` shortcodes.
=> Add OpenAPI shortcodes documentation

publish-technical-documentation/action.yml
It has limited installation so that it can only clone the repositories it needs:
- grafana/website-sync
- grafana/website
Tested in https://github.com/grafana/writers-toolkit/commit/82b7a14a102e5e19f4d2a023b9248a2400bab60d and https://github.com/grafana/writers-toolkit/actions/runs/10899782533/job/30245958284#step:3:622 which resulted in a 404 when trying to check out grafana/technical-documentation.
You can use the default GITHUB_TOKEN to check out the source repository.
=> Publish documentation using the GitHub App

docs/sources/review/lint-prose/rules.md, tools/cmd/generate-documentation/main.go, tools/cmd/generate-documentation/ruleSubstitution.tmpl, vale/Grafana/Admin.yml, vale/Grafana/Agentless.yml, vale/Grafana/DropDown.yml, vale/Grafana/EndToEnd.yml, vale/Grafana/MetaMonitoring.yml, vale/Grafana/Quickstart.yml, vale/Grafana/SelfManaged.yml, vale/Grafana/Shortcodes.yml
- Ensure all substitutions have exactly two format codes.
- Escape pipes in replacement regular expressions.
- Only transform placeholder variables and not all text between `<` and `>`
=> Fix some visual bugs in rule rendering

docs/sources/structure/topic-types/concept/index.md, docs/sources/whats-new.md, docs/sources/write/style-guide/word-list/index.md
Add guidance for naming best practice guidelines _Best practices_
=> Docs: Add Best practices title guidance

docs/sources/contribute/_index.md
Changes incoming in https://github.com/grafana/website/pull/22302/
Closes https://github.com/grafana/writers-toolkit/issues/883
I may have had a bit too much fun with shortcodes. Perhaps I should just update the wording instead?
=> Update documentation in preparation for changes to feedback links

docs/sources/write/grot-guides/index.md
The link was wrong in the first place and there is not a `guide` shortcode reference on https://grafana.com/docs/writers-toolkit/write/shortcodes/, only https://grafana.com/docs/writers-toolkit/write/shortcodes/#grot-guides which links back to this page.
=> Remove broken link

.github/workflows/add-to-docs-project.yml
**Why is the change needed, what does it improve?**
`send-slack-message` upstream action has a lot of breaking changes ([see here](https://github.com/grafana/shared-workflows/pull/534)). We need to make sure that all usages of our shared-workflow are pinned to avoid breakages.
=> chore: Pin `send-slack-message` workflow

.github/workflows/deploy-pr-preview.yml, .github/workflows/deploy-preview.yml, .gitignore, deploy-preview/build.sh, docs/sources/_index.md, home/robbymilo/grafana/grafana/docs/sources/content/docs/grafana/_index.md
for https://github.com/grafana/website/issues/10101
This PR fixes the shared content shortcodes in deploy previews by adding the `index_file` input param, and if true creates a custom `_index.md` file similar to the `make docs` command.
See https://github.com/grafana/grafana/pull/97355 for the fixed run.
Todo:
=> use custom _index.md for deploy previews

publish-technical-documentation/action.yml
This isn't often a failure case and causes a lot of noise for repositories with multiple documentation projects
=> Default to allowing no changes during sync

RELEASE.md, publish-technical-documentation-release/action.yaml, publish-technical-documentation-release/determine-release-branch
I'll use the documentation and new code to release a v2.0.0-rc.1 of the `publish-technical-documentation-*` actions.
I can then test that release candidate out in `grafana/grafana` and ensure that it works properly before release v2.0.0 proper.
Tags aren't necessarily made to the HEAD of the version branch. The documentation to be published is always on the HEAD of the release branch.
Because the workflow now uses regular expressions in Bash, inputs must now use Extended Regular Expression syntax.
Similar code was already used in [grafana/grafana](https://github.com/grafana/grafana/blob/ed2647b742c0db074c8833bde01886cedbc06e12/.github/workflows/publish-technical-documentation-release.yml#L54-L58) but wasn't ported to this composite action.
=> Check out the HEAD of the release branch for tag events

update-make-docs/action.yml
For some reason workflows using this action stopped running properly and I'd like to investigate why
=> Enable trace debugging using runner.debug

.github/workflows/test-publish-technical-documentation-release.yml, publish-technical-documentation-release/action.yaml, publish-technical-documentation-release/determine-release-branch
Makes it possible to develop and test this workflow in this repository so you don't have to publish the workflow and then test it somewhere else.
The dev/test workflow now looks like:
1. Create a branch `test/publish-technical-documentation/v<MAJOR>.<MINOR>.x`.
1. Iterate on the workflow or action.
1. To test push events, push the branch
1. To test tag events, tag the branch with `test/publish-technical-documentation/v<MAJOR>.<MINOR>.<PATCH>`
1. Check the workflow output in https://github.com/grafana/writers-toolkit/actions
I've added rulesets for the new branches and tags:
- https://github.com/grafana/writers-toolkit/settings/rules/2899360
- https://github.com/grafana/writers-toolkit/settings/rules/2899365
=> Add workflow to test publish-technical-documentation-release workflow

publish-technical-documentation-release/action.yaml
I managed to remove this step when I was moving bits around in #917.
Tested in https://github.com/grafana/grafana/actions/runs/12412933836/job/34653905262.
=> Restore missing has-matching-release-tag step

publish-technical-documentation-release/action.yaml
This workflow should have been using these credentials the whole time like `publish-technical-documentation-next` does.
I have created the protected branch [`publish-technical-documentation-release/v1`](https://github.com/grafana/writers-toolkit/tree/publish-technical-documentation-release/v1) so this change can be rolled out to all repositories using the v1 workflow.
I've used that branch to test this commit (cherry-picked to that branch) and verified that it works in https://github.com/grafana/pyroscope/actions/runs/12598364625/job/35206569003.
=> Use GitHub App token for publishing releases like for next documentation

vale/.vale.ini, vale/Makefile
Useful in https://github.com/grafana/beyla/pull/1497.
There's differences in Podman and Docker multi-arch build CLIs, so I've switched to the most commonly used to make sure others can use the targets if need be.
=> Add Hugo package to Vale config to make it easy for other users to fetch the package

.github/renovate-config.json5, .github/workflows/renovate.yml
Based on the workflow in https://github.com/grafana/shared-workflows/blob/main/.github/workflows/renovate.yml
=> Add Renovate workflow to keep actions, workflows, and tool dependencies up to date

.github/workflows/validate-documentation-inverse.yml, .github/workflows/validate-documentation.yml, vale-action/action.yml
Tested with string filter in https://github.com/grafana/writers-toolkit/actions/runs/12770075660?pr=950 and empty filter in https://github.com/grafana/writers-toolkit/actions/runs/12770308260/job/35594857756?pr=950
=> Quote environment variables to make the action easier to use with filters

vale/Google/WordList.yml, vale/Grafana/styles/Grafana/WordList.yml, vale/dictionary/c.jsonnet
This PR
- Adds _CSV file_ and _CSV files_ as suggested replacements for _CSV_ and _CSVs_ in Word List
- Removes _CSVs_ from dictionary
Should have done this instead of adding _CSVs_ to the dictionary per [PR 967](https://github.com/grafana/writers-toolkit/pull/967) 🙃
=> Docsc: Add CSV file and files to word list

docs/sources/review/lint-prose/rules.md, vale/Grafana/styles/Grafana/GrafanaCom.yml, vale/Grafana/styles/Grafana/WordList.yml, vale/tools/cmd/inhibit-rules/main.go
Closes https://github.com/grafana/writers-toolkit/issues/988
https://deploy-preview-writers-toolkit-1002-zb444pucvq-vp.a.run.app/docs/writers-toolkit/review/lint-prose/rules/#grafanagrafanacom
=> Add rule to catch use of `grafana.com`

publish-technical-documentation-release/action.yaml
Some steps don't need to run when a project only releases from tags and doesn't maintain release branches.
=> Fully implement `tags_only` release process

docs/make-docs
Ensures that `make docs` in the `grafana/fleet-management` repository mounts documentation at `/docs/grafana-cloud/send-data/fleet-management/`.
Works in https://github.com/grafana/fleet-management/pull/417 in conjunction with the changes in https://github.com/grafana/fleet-management/pull/417/files#diff-fb861c8ac0f20cff18de235abc95b7a640dc9812b4387dbe45a27b612690a0df
Relates to https://github.com/grafana/website/issues/23350
=> Mount fleet management docs in the Grafana Cloud location

docs/sources/review/lint-prose/_index.md
I need to also update the steps to tell a user to run `vale sync` after updating the repository
=> Update Vale configuration example

docs/sources/whats-new.md, docs/sources/write/shortcodes/index.md
Adding the `video-embed` shortcode to the Shortcodes page for easy access. I always look on this page for all shortcodes and I always have to go over to the Image and media guidelines page to find this shortcode.
=> Docs: Add video-embed shortcode to Shortcode page

.github/workflows/deploy-pr-preview.yml, .github/workflows/deploy-preview.yml, deploy-preview/build, deploy-preview/build.sh, deploy-preview/urls, docs/sources/_index.md
This lets us build multiples sources in a single deploy preview as demonstrated in https://github.com/grafana/mimir/pull/10580.
I also think it allows us to mount source projects into Grafana Cloud documentation directly instead of a publishing directory although it doesn't use Hugo mounts for that.
Let me know if you'd like me to test anything specifically out for you so you can be confident in the changes.
This can be rolled out safely as tested in:
- [Legacy inputs](https://github.com/grafana/fleet-management/actions/runs/13409179066/workflow?pr=490)
- [New inputs](https://github.com/grafana/writers-toolkit/actions/runs/13409334007/job/37455648763?pr=1014)
=> Replace individual inputs with JSON string array of inputs

docs/sources/contribute/_index.md, docs/sources/introduction/index.md
Inline shortcodes are powerful templating tools and allow source projects to iterate on HTML templates without a PR to the website repository.
However, by accident or malintent, they can be used break the website or expose information.
On the balance of things, the Docs Platform team believes that the risk outweighs the reward and will be disabling the feature.
The team believes it can support the prompt and safe creation of central shortcodes to satisfy the needs of the source projects.
All existing inline shortcodes have already been translated into central shortcodes that everyone can use.
Created-By: reverse-changes
Repository: grafana/writers-toolkit
Website-Pull-Request: https://github.com/grafana/website/pull/24705
=> Remove inline shortcodes

.github/workflows/validate-documentation.yml, vale-action/action.yml
Now we can report CodeQL issues with the docs (from Vale), it makes sense to track them on `main` so PRs can see if they introduced the issue or if it already existed.
=> Add support for workflow dispatch and running on main for documentation CI

vale-action/action.yml, vale/tools/cmd/filter-sarif/filter.go, vale/tools/cmd/filter-sarif/main.go
Chunks contain additional context can contain linting errors but that isn't part of a contributors patch.
=> Only keep lines that weren't pre-existing

.github/workflows/dictionaries.yml, .github/workflows/prettier.yml, prettier/action.yml, vale/Grafana/styles/Grafana/Simple.yml
Prettier changes tested with `gh workflow run prettier.yml --ref jdb/2025-04-use-docs-platform-github-app --json <<<'{ "path": "vale" }'` when the branch pointed at [`a86266d` (#1145)](https://github.com/grafana/writers-toolkit/pull/1145/commits/a86266deb4c8a4873ff21476650b311fa754016c).
=> Use docs-platform-team GitHub App for repo workflows

docs/sources/write/reuse-content/_index.md
=> Document when to use `shared` or `docs/copy` shortcodes

docs/sources/structure/topic-types/task/index.md, docs/sources/write/image-guidelines/index.md, docs/sources/write/style-guide/capitalization-punctuation/index.md, docs/sources/write/style-guide/voice-tone-guidelines/index.md
Add a link to the Google developer documentation style guide to the headings section and add some additional guidance to not use gerunds in headings.
=> [DOC] Add links to heading guidelines

docs/sources/write/shortcodes/index.md
Without the comment syntax, Hugo renders the shortcode rather than the text representing the shortcode in the source material.
Also:
[Update CTA shortcodes copy to more accurately describe the output](https://github.com/grafana/writers-toolkit/pull/1193/commits/154d734a94677a8391325568d45d346e5c7edc4d) 
154d734
They used to be admonitions, now they are CTAs
=> Fix `docs/learning-journeys` example rendering

.github/workflows/docs-ci.yml, .github/workflows/validate-documentation-inverse.yml, .github/workflows/validate-documentation.yml, docs/sources/_index.md
Then we can use the same CI in other repos.
- https://github.com/grafana/writers-toolkit/actions/runs/15605390018/job/43953571237?pr=1194
- https://github.com/grafana/writers-toolkit/actions/runs/15605390018/job/43953571239?pr=1194
- https://github.com/grafana/writers-toolkit/actions/runs/15605390018/job/43953571288?pr=1194
=> Refactor documentation CI into reusable workflow

.github/renovate-config.json5
Documented in https://github.com/grafana/shared-workflows/pull/1164
=> Update Renovate config to handle shared-workflows tag convention

.github/workflows/docs-ci.yml, .github/workflows/validate-documentation.yml, build-website/action.yml, build-website/shared-shortcode.js
Will drop some commits before merging that were used to test the behavior.
Relates to https://raintank-corp.slack.com/archives/C07R2REUULS/p1752245272948599?thread_ts=1752244152.551779&cid=C07R2REUULS
=> Add documentation CI step that checks for renamed files containing the shared shortcode

docs/sources/write/style-guide/inclusive-writing/index.md
This pull request includes documentation improvements focused on clarity and accessibility, specifically:
Updated the section in the style guide to advise against using spatial directional language (like "above", "below", "to the right") and provided alternative phrases that are more accessible to users with visual disabilities or those using screen readers.
Closes https://github.com/grafana/website/issues/27507
=> Update style guide to avoid directional language

vale/Grafana/styles/config/dictionaries/en_US-grafana.dic, vale/dictionary/p.jsonnet
vale is complaining in [this PR](https://github.com/grafana/website/pull/27285/files), particularly about using "PDC" in headings. Add the term to the vale dictionary
=> add 'PDC' to vale dictionary
