- docs/sources/writing-guide/image-guidelines/index.md
Added info about the vimeo short code for embedding videos.
> Add video info

- docs/sources/writing-guide/image-guidelines/index.md
Added escape characters to the example of the video so it renders properly.
> fix video example

- docs/sources/writing-guide/markdown-guide/index.md
the note says "Use unordered lists whenever the items have no particular sequence." and then the items are named "first" and "last" :-)
So, I just suggest to use different list items :-D
> rename items in unordered list

- docs/sources/style-guide/capitalization-punctuation/index.md
> Change formatting guidance from italic to bold.

- docs/sources/writing-guide/front-matter/index.md
> Update guidelines for aliases considering versions

- docs/sources/writing-guide/references/index.md
I spent far too long trying to get this to build and missed the obvious, so including it here for others to hopefully save some time.
> Add gotcha about quotes to troubleshooting section

- docs/docs.mk
- docs/sources/writing-guide/contribute-documentation/index.md
Podman has the upside that containers can either be run as root or in rootless mode.
> Update initial contribution documentation to favor Podman

- docs/sources/writing-guide/markdown-guide/index.md
> Markdown, document the standard markdown flavor

- docs/sources/writing-guide/seo-link-text/index.md
- docs/sources/writing-guide/useful-link-text/index.md
Source content is at (internal doc) https://docs.google.com/document/d/1KODybKQA5lL5v5wRqcq4heO7Ie8MGt0M6aTKabtVcwI/edit.
> Incorporate useful link text.

- docs/docs.mk
- docs/sources/writing-guide/contribute-documentation/index.md
> Document contributing across versions

- docs/sources/style-guide/_index.md
Per discussion last month in Slack, issuing PR at Chris's request.
> Docs: Fix reference to Google style

- docs/sources/writing-guide/shortcodes/index.md
Depends on https://github.com/grafana/website/pull/12080
> Update `section` shortcode to explain `ordered` parameter

- docs/sources/writing-guide/front-matter/index.md
> Reorganize front matter reference for anchor linking

- docs/sources/writing-guide/documentation-structure/index.md
This PR adds a list of topics to create a table of contents for any document structure. This is a first draft and needs to be reviewed to make sure information has been captured correctly. 
Notes for reviewers: 
* Please add any example pages to the Example link column
* There are missing descriptions. Please suggest or add any info. 
Fixes #207
> Add TOC terms

- docs/sources/writing-guide/reuse-directories/index.md
- docs/sources/writing-guide/reuse-shared-content/index.md
Closes https://github.com/grafana/technical-documentation/issues/610
> Document how to reuse directories of content with Hugo mounts

- docs/sources/writing-guide/shortcodes/index.md
https://github.com/grafana/website/pull/12542
> Add withDescriptions parameter to section shortcode

- docs/docs.mk
- docs/sources/writing-guide/tooling-and-workflows/run-a-local-webserver/index.md
Closes https://github.com/grafana/technical-documentation/issues/667
> Update documentation to explain how to build multiple projects simultaneously

- docs/sources/writing-guide/front-matter/index.md
> Document how to test an alias

- docs/sources/writing-guide/references/index.md
Hopefully this page can be a source of reference for all writers so we can share a common understanding of links.
Please ensure that the content makes sense to you and if not, make sure to ask the questions on this PR.
> Update link and cross references documentation

- .github/workflows/test.yml
- docs/CHANGELOG.md
- docs/docs.mk
- docs/make-docs
- docs/variables.mk
> Update make-docs procedure to support doc-validator 2.0.x

- docs/sources/writing-guide/shortcodes/index.md
> Document responsive-table shortcode

- docs/sources/writing-guide/front-matter/index.md
> Add clarification to metadata topic

- docs/sources/style-guide/style-conventions/index.md
> Document ordered list style

- docs/CHANGELOG.md
- docs/docs.mk
- docs/make-docs
- docs/sources/writing-guide/tooling-and-workflows/validate-technical-documentation/_index.md
- docs/sources/writing-guide/tooling-and-workflows/validate-technical-documentation/errata.md
- docs/sources/writing-guide/tooling-and-workflows/validate-technical-documentation/index.md
- Fix quotation of shell arguments
- Document `doc-validator` Make target
- Remove `doc-validator/%` target
> Document doc-validator

- docs/sources/writing-guide/front-matter/index.md
> Document date front matter

- docs/sources/writing-guide/about-documentation-design/index.md
> Fix broken link formatting.

- docs/sources/style-guide/write-for-developers/index.md
Format for recommended PLACEHOLDER is updated to reflect most recent decision by style council.
> Docs: Update placeholder style per roundtable

- docs/sources/writing-guide/tooling-and-workflows/validate-technical-documentation/errata.md
https://github.com/grafana/technical-documentation/pull/773
> Support linking from branch bundles also

- docs/sources/write/front-matter/index.md
> Add examples of relative aliases

- docs/sources/write/markdown-guide/index.md
> Add explanation of two link styles

- docs/sources/contribute-documentation/_index.md
- docs/sources/write/tooling-and-workflows/_index.md
- Added information about git force push (copied over from our internal wiki)
- Updated headings
> Add information about git force push

- docs/sources/write/shortcodes/index.md
for https://github.com/grafana/website/issues/1135
related to https://github.com/grafana/website/pull/15187
> document code shortcode

- docs/sources/_index.md
- docs/sources/write/_index.md
- docs/sources/write/style-guide/capitalization-punctuation/index.md
Added a few sentences about using US English.
> Add US English

- docs/sources/write/shortcodes/index.md
for https://github.com/grafana/website/issues/13586
needs https://github.com/grafana/website/pull/15294
> document term shortcode

- docs/sources/write/shortcodes/index.md
for https://github.com/grafana/website/issues/15036
needs https://github.com/grafana/website/pull/15422
> document collapse shortcode

- docs/sources/write/shortcodes/index.md
- Add demonstration of `term` shortcode
- Describe where the glossary is stored and how to handle multiple definitions
>  Describe where the glossary is stored and how to handle multiple definitions

- docs/sources/write/shortcodes/index.md
Add some basic information about ways you can't use this shortcode.
> Add guidance for collapse shortcode

- docs/sources/review/doc-validator/_index.md
- docs/sources/review/lint-prose/index.md
- docs/sources/review/run-a-local-webserver/index.md
- docs/sources/shared/make-help.md
> Use shared page for duplicate GNU Make help content

- vale/Grafana/WordList.yml
@imatwawana I'm not sure if we need to add this to our public word list documentation given that it is already covered in https://developers.google.com/style/word-list#backend and https://developers.google.com/style/word-list#frontend. WDYT?
Closes https://github.com/grafana/technical-documentation/issues/261
> Add backend and frontend to wordlist

- docs/sources/write/style-guide/ux-writing/index.md
Clarify that product names are considered proper nouns in UX writing section
> Add product name guidance

- vale/Grafana/Acronyms.yml
> Add exceptions for spelling out common abbreviations

- docs/sources/write/markdown-guide/index.md
> Add instruction for multiple paragraphs with automatic numbering

- docs/sources/write/markdown-guide/index.md
Blocked by https://github.com/grafana/website/issues/15496.
> Docs: Add syntax for writing a sub-task

- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/wordlist
> Add misconfiguration and misconfigurations to dictionary

- vale/Grafana/Headings.yml
- vale/Grafana/WordList.yml
- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/wordlist
> Add Amazon Kinesis Data Firehose terms "Firehose" and "Kinesis"

- vale/dictionaries/en_US-grafana.dic
> Doc: Add the state of not aggregated or having been disaggregated

- docs/sources/write/style-guide/style-conventions/index.md
This PR adds a simple one-line guideline for sorting lists (and table rows).
> Add advice for sorting lists

- docs/sources/write/style-guide/style-conventions/index.md
I merged too quickly... this PR fixes a simple spelling mistake in the heading.
> Fix spelling mistake in heading

- docs/sources/structure/topic-types/tutorial/index.md
- docs/sources/write/style-guide/style-conventions/index.md
- docs/sources/write/tooling-and-workflows/_index.md
- vale/Grafana/ReferTo.yml
Motivation is https://grafana.com/docs/writers-toolkit/write/style-guide/style-conventions/#links-and-references
> Add rule to encourage "refer to"

- docs/sources/write/image-guidelines/index.md
- docs/sources/write/style-guide/ux-writing/index.md
- docs/static/templates/visualization-template.md
- vale/Grafana/Please.yml
- Add Grafana.Please rule
- Fix instances of please
From Style roundtable: https://docs.google.com/document/d/1uCjtHEy0lpZggkpgsLDjWwxV9K6h7vcsG2dy4TOS6EA/edit#heading=h.evvgwcha9845
> Add `Grafana.Please` Vale rule

- docs/sources/contribute-documentation/contribute-release-notes/index.md
> Update links to new page that has consistent naming

- vale/Grafana/WordList.yml
The English terms are more specific and easier to understand than the Latin.
> Prefer 'free-form' or 'user-written' over ad-hoc

- docs/sources/contribute-documentation/contribute-release-notes/index.md
To address a question from a confused user: https://raintank-corp.slack.com/archives/C010WU9Q5TJ/p1704381303827759
> Docs: Make clear the Internal Information is not made public in What's New

- docs/sources/contribute-documentation/contribute-release-notes/index.md
- docs/sources/write/style-guide/inclusive-writing/index.md
Per a discussion in the style roundtable meeting.
> Docs: add directional language guidance

- docs/sources/write/image-guidelines/index.md
- vale/Grafana/Acronyms.yml
- vale/Grafana/Headings.yml
> Document `youtube` shortcode parameters

- docs/sources/write/image-guidelines/index.md
Closes https://github.com/grafana/writers-toolkit/issues/182
> Document one reason for avoiding GIFs

- docs/sources/write/style-guide/style-conventions/index.md
> Add code text formatting guidelines

- .github/workflows/validate-documentation.yml
- .vale.ini
- docs/make-docs
- docs/sources/about-grafana-docs/index.md
- docs/sources/write/style-guide/ux-writing/index.md
- docs/variables.mk
- vale/.vale.ini
- vale/.vale.jsonnet
- vale/Dockerfile
- vale/Makefile
Also use platform appropriate images for faster linting.
> Update Vale and `reviewdog` to latest releases

- vale/dictionaries/en_US-grafana.aff
- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/wordlist
- autoscale
- autoscaled
- autoscaling
- autoscaler
- autoscales
Closes https://github.com/grafana/writers-toolkit/issues/421
> Add autoscale verb and affixed forms to dictionary

- vale/dictionaries/en_US-grafana.aff
- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/wordlist
Closes https://github.com/grafana/writers-toolkit/issues/420
> Add prefix rule for "de-" and add deprovisioned to dictionary

- vale/Grafana/Headings.yml
- vale/Grafana/WordList.yml
- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/wordlist
> Add Promtail to dictionary

- .github/workflows/validate-documentation.yml
> Use default filter mode of only added/modified hunks

- docs/sources/contribute-documentation/contribute-release-notes/index.md
Update versioned release process
> Update versioned release process

- vale/.reviewdog.yml
> Update Vale image reviewdog command

- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/en_US-grafana.wordlist
This is a well established term in GDB debugging.
For example, https://www.acrc.bris.ac.uk/acrc/RedHat/rhel-gdb-en-4/tracepoints.html.
> Add tracepoint and its plural form to the dictionary

- vale/Grafana/WordList.yml
- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/en_US-grafana.wordlist
Catch _K8s_ and _kubernetes_ also.
Closes https://github.com/grafana/writers-toolkit/issues/462.
> Sort lines without case folding, update Kubernetes substitutions, and add more words to dictionary

- docs/make-docs
> Update support for plugins monorepo now that multiple projects have been moved into it

- .reviewdog.yml
- docs/sources/write/style-guide/word-list/index.md
> Add React to word list

- .github/workflows/review.yml
> Create individual issues for each page to be reviewed

- docs/sources/_index.md
- docs/sources/about-grafana-docs/index.md
- docs/sources/contribute-documentation/_index.md
- docs/sources/structure/topic-types/_index.md
- docs/sources/write/image-guidelines/index.md
- docs/sources/write/markdown-guide/index.md
- docs/sources/write/style-guide/_index.md
- vale/Grafana/Acronyms.yml
- vale/Grafana/GoogleColons.yml
- vale/Grafana/Headings.yml
- vale/google.jsonnet
Closes https://github.com/grafana/writers-toolkit/issues/481
Closes https://github.com/grafana/writers-toolkit/issues/482
Closes https://github.com/grafana/writers-toolkit/issues/483
> Review some docs pages

- .github/workflows/dictionaries.yml
- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/en_US-grafana.wordlist
This PR adds "KPI" and "KPIs" to the wordlist so that they won't be flagged by the linter.
> docs: adds terms to wordlist

- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/en_US-grafana.wordlist
Defined in https://github.com/grafana/website/pull/18319
> Add spanset to dictionary

- docs/sources/contribute-documentation/contribute-release-notes/index.md
Add warning that you won't see a future-dated What's new entry in a preview build
> Docs: add future dated entry preview warning

- docs/sources/review/doc-validator/errata.md
Changes made in https://github.com/grafana/technical-documentation/pull/902.
Closes https://github.com/grafana/writers-toolkit/issues/508.
> Review "Errata for `doc-validator`" page

- vale/Grafana/Timeless.yml
Resolves https://github.com/grafana/writers-toolkit/issues/485.
> Downgrade Grafana.Timeless to be a suggestion

- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/en_US-grafana.wordlist
https://en.wikipedia.org/wiki/Serverless_computing
> Add "serverless" to dictionary

- vale/Grafana/Headings.yml
- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/en_US-grafana.wordlist
(cherry picked from commit 5e006b08cc492840a6c3b85b4d234f25742bcd79)
> Add some terminology used frequently in Mimir documentation

- vale/Grafana/WordList.yml
https://github.com/grafana/website/pull/18262#discussion_r1491625281
> Remove requirement to say 'static external IP address'

- docs/sources/shared/hugo-error-example-bad-link.md
Closes https://github.com/grafana/writers-toolkit/issues/517
> Review Hugo relref error example

- docs/sources/shared/index.md
- tools/cmd/review/main.go
And exclude it from the need to review in the future since it isn't really content.
Closes https://github.com/grafana/writers-toolkit/issues/516
> Review "shared" index page

- docs/sources/structure/topic-types/_index.md
https://grafana.com/docs/writers-toolkit/structure/topic-types/
> Fix typo affecting rendering of description list

- docs/sources/structure/about-documentation-design/index.md
Closes https://github.com/grafana/writers-toolkit/issues/538.
- Justifies use of first person
- Use correct emphasis for phrases in sentences.
> Review "About our documentation design" page

- docs/make-docs
Added in https://github.com/grafana/website/pull/17561
> Remove warnings from missing lookups on docs homepage

- docs/sources/contribute/_index.md
- docs/sources/contribute/release-notes/index.md
- docs/sources/get-started/_index.md
- docs/sources/introduction/index.md
- docs/sources/review/doc-validator/errata.md
- docs/sources/write/markdown-guide/index.md
- docs/sources/write/reuse-content/_index.md
- docs/sources/write/reuse-content/reuse-shared-content/index.md
- docs/sources/write/shortcodes/index.md
Fix broken links that are currently relying on redirects and anchors that are out of date.
> Reorganize docs to have friendlier URL paths 

- docs/sources/write/deprecate-remove/index.md
Closes #563 
- Fix front matter
- Use correct emphasis for words
- Update linter exceptions for new rule names
- Correct references to the Grafana Labs documentation team
> Review "Deprecate or remove content" page

- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/en_US-grafana.wordlist
https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/
> Add CRD to and plural form dictionary

- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/en_US-grafana.wordlist
"VUH" is an acronym for Virtual User hours that we use regularly in the k6 docs.
> Add "VUH" to wordlist

- docs/sources/write/image-guidelines/index.md
- docs/sources/write/shortcodes/index.md
Closes https://github.com/grafana/writers-toolkit/issues/511
> Move video shortcodes to shortcodes page

- docs/sources/structure/_index.md
@knylander-grafana has indicated that this is no longer needed in #532.
Closes #532.
> Remove comment

- vale/dictionaries/en_US-grafana.dic
- vale/dictionaries/en_US-grafana.wordlist
> Add Couchbase to dictionary

- docs/sources/write/reuse-content/_index.md
- Use consistent alias format
- Reorder a sentence for clarity
Closes https://github.com/grafana/writers-toolkit/issues/586
> Review "Reuse content" page

- docs/sources/write/front-matter/index.md
- Clean up use of bold for emphasis
- Use semantic line breaks
- Correct some statements
- Use contractions
Closes https://github.com/grafana/writers-toolkit/issues/569
> Review "Front matter" page

- vale/Grafana/GoogleOrdinal.yml
- vale/Grafana/Ordinal.yml
- vale/google.jsonnet
> Update ordinal rule to match Writers' Toolkit guidance 

- vale/dictionaries/Makefile
- vale/dictionaries/en_US-grafana.dic
- vale/dictionary.jsonnet
- https://en.wikipedia.org/wiki/Apdex
- https://en.wikipedia.org/wiki/Traceroute
> Add Appdex and traceroute to dictionary

- vale/dictionary.jsonnet
https://www.merriam-webster.com/dictionary/composable
https://github.com/grafana/website/pull/19432/files#r1567336368
> Add composable

- docs/make-docs
> Add SELinux label support to container volume mounts

- vale/Grafana/ProductPossessives.yml
- vale/Makefile
- vale/dictionaries/en_US-grafana.dic
- vale/dictionary.jsonnet
https://velero.io/
Closes https://github.com/grafana/writers-toolkit/issues/641
> Add Velero product to dictionary

- docs/sources/write/style-guide/ui-elements/index.md
> Review UI elements list page

- docs/sources/write/style-guide/style-conventions/index.md
- Use contractions
- Use semantic line breaks
- Update admonition syntax
Closes https://github.com/grafana/writers-toolkit/issues/625
> Review Style conventions page

- docs/sources/write/deprecate-remove/index.md
https://raintank-corp.slack.com/archives/C5PG2JK8W/p1715799930387939
> Document procedure for removing a page

- docs/sources/review/backport-changes/index.md
- Improve description
- Document that a maintainer can advise on backporting
Rest LGTM.
Closes https://github.com/grafana/writers-toolkit/issues/665.
> Review 'Backport changes' page

- docs/sources/review/cla-assistant/index.md
- Add more context to description
- Add link to Grafana Labs CLA
Rest LGTM.
Closes https://github.com/grafana/writers-toolkit/issues/671
> Review 'CLA Assistant' page

- docs/sources/review/doc-validator/_index.md
- Add more context to description
Rest LGTM.
Closes https://github.com/grafana/writers-toolkit/issues/672
> Review 'Automated validation' page

- docs/sources/shared/hugo-error-example-bad-link.md
- Update links to uses
- Use more readable language explaining how to resolve the error
Closes https://github.com/grafana/writers-toolkit/issues/681
> Review Hugo output shared page

- docs/sources/review/test-documentation-changes/index.md
- Use semantic line breaks.
- Avoid passive voice
- Clarify that the note only refers to Grafana tutorials
Closes https://github.com/grafana/writers-toolkit/issues/680
> Review 'Test documentation changes' page

- docs/sources/structure/about-documentation-design/index.md
- Update Vale linting exclusion
- Simplify some language for readability
Rest LGTM.
Closes https://github.com/grafana/writers-toolkit/issues/689
> Review 'About documentation design' page

- docs/sources/structure/topic-types/_index.md
- Replaces relrefs with URLs
Rest LGTM
Closes https://github.com/grafana/writers-toolkit/issues/693
> Review 'Topic types' page

- docs/sources/structure/topic-types/reference/index.md
- Fix reference to index file
Rest LGTM
Closes https://github.com/grafana/writers-toolkit/issues/694
> Review 'Reference topic' page

- docs/sources/write/style-guide/inclusive-writing/index.md
- Make description more comprehensive and suited to the search engine context in which it is found.
- Remove smart quotes
- Use semantic line breaks
- Remove overly friendly language
Closes #623
> Review 'Inclusive writing' page

- vale/Grafana/DatadogProxy.yml
- vale/fixtures/Grafana/DatadogProxy/.vale.ini
- vale/fixtures/Grafana/DatadogProxy/testinvalid.md
- vale/fixtures/Grafana/DatadogProxy/testvalid.md
https://github.com/grafana/website/pull/20047#discussion_r1627710514
> Add rule to catch correct spelling of Datadog proxy

- docs/sources/review/test-documentation-changes/index.md
- docs/sources/write/reuse-content/reuse-shared-content/index.md
- vale/Grafana/CommandLinePrompts.yml
- vale/fixtures/Grafana/CommandLinePrompts/.vale.ini
- vale/fixtures/Grafana/CommandLinePrompts/testinvalid.golden
- vale/fixtures/Grafana/CommandLinePrompts/testinvalid.md
- vale/fixtures/Grafana/CommandLinePrompts/testvalid.md
https://grafana.com/docs/writers-toolkit/write/style-guide/write-for-developers/#command-lines
> Add rule to lint for use of command line prompts

- docs/sources/structure/topic-types/task/index.md
Use placeholder syntax.
Rest looks good to me.
Closes https://github.com/grafana/writers-toolkit/issues/707
> Review 'Task topic' page

- docs/sources/structure/topic-types/visualization/index.md
Use placeholder syntax.
Rest looks good to me.
Closes https://github.com/grafana/writers-toolkit/issues/712
> Review 'Visualization topic' page

- docs/sources/review/cla-assistant/index.md
- docs/sources/review/doc-validator/_index.md
- docs/sources/review/lint-prose/index.md
- docs/sources/review/test-documentation-changes/index.md
- docs/sources/shared/refs-example.md
- docs/sources/structure/topic-types/tutorial/index.md
- docs/sources/write/links/_index.md
- docs/sources/write/shortcodes/index.md
- docs/sources/write/tooling-and-workflows/index.md
I had misremembered the guidance in
https://grafana.com/docs/writers-toolkit/write/style-guide/write-for-developers/#placeholder-variables
> Use correct placeholder syntax

- docs/sources/structure/topic-types/tutorial/index.md
Update one link to avoid a redirect
Rest looks good to me.
Closes https://github.com/grafana/writers-toolkit/issues/706
> Review 'Tutorial topic' page

- docs/sources/structure/topic-types/visualization/index.md
Remove to-do note since issue is open
> Docs: remove to do note

- vale/dictionaries/en_US-grafana.dic
- vale/dictionary.jsonnet
https://en.wiktionary.org/wiki/callee
> Add callee to the dictionary

- vale/dictionaries/en_US-grafana.dic
- vale/dictionary.jsonnet
Related to https://github.com/grafana/website/pull/20024, I forgot to add this one. 🤓 
Word is related to Web Vitals, [Largest Contentful Paint](https://web.dev/articles/optimize-lcp) (LCP).
> Add contentful to dictionary.jsonnet

- vale/Grafana/AndOr.yml
- vale/fixtures/Grafana/AndOr/.vale.ini
- vale/fixtures/Grafana/AndOr/testinvalid.golden
- vale/fixtures/Grafana/AndOr/testinvalid.md
- vale/fixtures/Grafana/AndOr/testvalid.md
Outcome of https://docs.google.com/document/d/1uCjtHEy0lpZggkpgsLDjWwxV9K6h7vcsG2dy4TOS6EA/edit#heading=h.valhzaozfw5m
> Add rule for catching and/or

- vale/Grafana/Admin.yml
- vale/Grafana/WordList.yml
- vale/fixtures/Grafana/Admin/.vale.ini
- vale/fixtures/Grafana/Admin/testinvalid.golden
- vale/fixtures/Grafana/Admin/testinvalid.md
- vale/fixtures/Grafana/Admin/testvalid.md
Outcome from https://docs.google.com/document/d/1uCjtHEy0lpZggkpgsLDjWwxV9K6h7vcsG2dy4TOS6EA/edit#heading=h.valhzaozfw5m
> Add Admin rule that clarifies when it's OK to use admin instead of administrator

- docs/sources/write/image-guidelines/index.md
- Include more context in the description
- Remove use of "simple"
- Simplify some language for readability
- Consolidate video sections
- Use consistent placeholder variable notation
- Use a high quality example of alt text
Closes https://github.com/grafana/writers-toolkit/issues/730
> Review 'Media guidelines' page

- docs/sources/review/lint-prose/_index.md
Fleshing this out a little, because for some reason I did NOT understand how to do this when I first read it and just copy/pasted the example.  Which of course, isn't how it works....
> docs: extend skip rules example

- docs/sources/shared/refs-example.md
Closes https://github.com/grafana/writers-toolkit/issues/742
LGTM
> Review 'An example of the `refs` front matter'

- docs/sources/write/links/_index.md
Closes https://github.com/grafana/writers-toolkit/issues/746
- Add some semantic line breaks
- Replace semicolon with two sentences
Rest LGTM
> Review 'Links' page

- docs/sources/write/markdown-guide/index.md
- Add semantic line breaks
- Add some more meaningful alt text
- Make some clarifying edits
The rest LGTM
Closes https://github.com/grafana/writers-toolkit/issues/752
> Review 'Markdown guide'

- docs/sources/write/reuse-content/reuse-directories/index.md
- Avoid some passive voice
- Correct name of Hugo feature
- Make some clarifying edits
The rest LGTM
Closes https://github.com/grafana/writers-toolkit/issues/753
> Review 'Reuse directories of content'

- docs/sources/write/_index.md
- Update link text to match destination title
Rest LGTM
Closes https://github.com/grafana/writers-toolkit/issues/552
> Review 'Write' page

- docs/sources/write/style-guide/_index.md
LGTM
Closes https://github.com/grafana/writers-toolkit/issues/761
> Review 'Style guide' page

- docs/sources/write/style-guide/inclusive-writing/index.md
I forgot to set the `review_date` metadata in https://github.com/grafana/writers-toolkit/pull/657
Closes: https://github.com/grafana/writers-toolkit/issues/762
> Re-review 'Inclusive writing' page

- docs/sources/write/style-guide/voice-tone-guidelines/index.md
> Review 'Voice and tone guidelines'

- docs/sources/write/style-guide/write-for-developers/index.md
- Include company name context in description
- Use semantic line breaks
- Replace relref shortcode with URLs
- Update Vale rule exceptions
- Use consistent placeholder variable syntax
> Review 'Write for developers' page

- docs/sources/write/style-guide/capitalization-punctuation/index.md
- docs/sources/write/style-guide/style-conventions/index.md
Adds guidance for formatting abstract UI concepts and bold formatting in tables
> Docs: add text formatting rules

- docs/sources/write/image-guidelines/index.md
The content was moved to https://grafana.com/docs/writers-toolkit/write/image-guidelines/#video-guidelines
> Remove empty "Video" section

- docs/sources/write/links/_index.md
https://raintank-corp.slack.com/archives/C01EK60DKC5/p1721148121117609
> Try to clarify when to use ref URIs

- vale/Grafana/Acronyms.yml
- vale/Grafana/Headings.yml
- vale/dictionaries/en_US-grafana.dic
- vale/dictionary.jsonnet
https://en.wikipedia.org/wiki/Virtual_private_cloud
> Add VPC to the Vale dictionary

- docs/sources/structure/topic-types/concept/index.md
- docs/sources/structure/topic-types/reference/index.md
- docs/sources/structure/topic-types/section/index.md
- docs/sources/structure/topic-types/task/index.md
- docs/sources/structure/topic-types/tutorial/index.md
- docs/sources/structure/topic-types/visualization/index.md
- docs/static/templates/section.md
Document the other kind of page we have in our documentation: section pages. Not all section pages are landing pages but I think we're moving that way so I've only focused on landing pages.
I'm not sure this needs to be comprehensive, I think it provides value by completing the set of possible page types. 
> Draft section page documentation

- docs/sources/write/shortcodes/index.md
- publish-technical-documentation-release/action.yaml
- publish-technical-documentation/action.yml
- tools/.golangci.yml
- vale/Grafana/AndOr.yml
- vale/Grafana/DatadogProxy.yml
- vale/Grafana/HTTP.yml
- vale/Grafana/Quickstart.yml
Upstream updates of https://github.com/grafana/website/pull/21322.
> update youtube shortcode args

- docs/sources/get-started/_index.md
- docs/sources/review/lint-prose/rules.md
- docs/sources/whats-new.md
- vale/Grafana/Exclamation.yml
- vale/Grafana/GoogleExclamation.yml
- vale/google.jsonnet
Based on the Style roundtable outcome in https://docs.google.com/document/d/1uCjtHEy0lpZggkpgsLDjWwxV9K6h7vcsG2dy4TOS6EA/edit#heading=h.9fvlhmlt68gs.
> Relax exclamation rule and note it in a new What's new page

- docs/sources/_index.md
- docs/sources/contribute/_index.md
- docs/sources/contribute/release-notes/index.md
- docs/sources/write/front-matter/index.md
- docs/sources/write/links/useful-link-text.md
- docs/sources/write/reuse-content/_index.md
- docs/sources/write/tooling-and-workflows/index.md
- Review "Front matter" page
- Minor rewording for clarity.
- Use double quotes for quoting phrases.
- Use contractions.
- Remove "About" from concept topic title in the example.
Rest LGTM.
Closes https://github.com/grafana/writers-toolkit/issues/774.
- Review "Reuse content" page
- Fix link anchor.
Rest LGTM.
Closes https://github.com/grafana/writers-toolkit/issues/775.
- Review "Tooling and workflows" page
- Avoid semicolon.
- Prefer "US English" over "American English".
- Clean up some console output for readability.
- Remove "simply" and clarify `--ff-only` flage behavior.
Rest LGTM.
Closes https://github.com/grafana/writers-toolkit/issues/776.
- Review "Useful link text" page
- Rename to reflect that it's a concept topic.
Rest LGTM.
Closes …
> Review some pages

- docs/sources/structure/topic-types/tutorial/index.md
- docs/sources/write/front-matter/index.md
Closes https://github.com/grafana/writers-toolkit/issues/816.
> Note and document the two forms of cascading front matter

- docs/sources/write/markdown-guide/index.md
Also specifically note not to use `<br>` HTML elements.
> Link to Google documentation style guide for table style

- vale/dictionaries/en_US-grafana.dic
- vale/dictionary/o.jsonnet
https://www.dictionary.com/browse/onboard
https://github.com/grafana/website/pull/21480#pullrequestreview-2279581660
> Add onboard, onboarded, and onboarding to dictionary

- docs/sources/review/backport-changes/_index.md
- docs/sources/review/backport-changes/install-the-workflow.md
Closes https://github.com/grafana/writers-toolkit/issues/787.
> Document how to install the backport workflow

- docs/sources/whats-new.md
- docs/sources/write/style-guide/word-list/index.md
- vale/Grafana/EndToEnd.yml
- vale/Grafana/MetaMonitoring.yml
Added three words to the word list, based on Style roundtable meeting on 09-05-2024.
> Added guidance for self-managed, end-to-end, and meta-monitoring

- .github/workflows/backport.yml
- .github/workflows/issue_and_pr_commands.yml
> Use issue-commands GitHub App

- publish-technical-documentation/action.yml
Reverts grafana/writers-toolkit#846
> Revert "Publish documentation using the GitHub App"

- publish-technical-documentation/action.yml
Reverts grafana/writers-toolkit#855
> Revert "Revert "Publish documentation using the GitHub App""

- .github/workflows/add-to-docs-project.yml
- add-to-docs-project/package-lock.json
- add-to-docs-project/package.json
- [Set engines version requirements for Node and npm](https://github.com/grafana/writers-toolkit/commit/29c44566b26a1bf165108716519f20c9fcc9a7d4) 
- [Add caching of npm modules](https://github.com/grafana/writers-toolkit/commit/e07a0e2d6e29236e8e10626ba3ed09ccc4cca21b) 
- [Ensure a clean install of npm modules for consistency](https://github.com/grafana/writers-toolkit/commit/596de4fd60eaec84921971970e14f5bcb0e828d0)
Closes https://github.com/grafana/writers-toolkit/issues/873
Thanks to @tolzhabayev for explaining the improvements
> Improve consistency and efficiency of CI execution

- docs/sources/write/tooling-and-workflows/index.md
I've also simplified the steps for generally updating a branch by removing superfluous commands and extraneous explanation of flag behavior.
> Note how to update contributors' branches

- docs/sources/contribute/release-notes/index.md
- docs/sources/whats-new.md
Also fix broken link.
Do we want a What's new entry?
> Encourage use of paragraphs in What's new notes

- docs/sources/whats-new.md
- docs/sources/write/shortcodes/index.md
for https://github.com/grafana/website/issues/20059
> document column-list shortcode

- docs/sources/write/front-matter/index.md
Closes https://github.com/grafana/writers-toolkit/issues/870
> Document how to use labels

- vale/Grafana/Headings.yml
- vale/dictionary/b.jsonnet
Add BoringCrypto to dictionary and add a heading exception.
> Add BoringCrypto to dictionary

- .github/workflows/deploy-preview.yml
for https://github.com/grafana/website/issues/10101
Thanks to @nate-walters-grafana for this one.
> check if deploy preview service exists before attempting delete

- docs/sources/contribute/release-notes/index.md
The previous link pointed to the old wiki.
> Fix broken link

- .github/PULL_REQUEST_TEMPLATE/default.md
Primarily to nudge behavior as we share code ownership.
> Add PR template

- publish-technical-documentation-release/action.yaml
> Update action inputs descriptions to describe the required regexp syntax

- docs/make-docs
They're now in the plugins monorepo.
Clears up the updates in https://github.com/grafana/mimir/pull/9078/ and https://github.com/grafana/plugins-private/pull/2688/.
> Remove special cases for Oracle and Datadog plugin

- docs/sources/structure/topic-types/section/index.md
> Fix link to section page template

- vale/Grafana/Paragraphs.yml
- vale/config/scripts/Paragraphs.tengo
- vale/config/scripts/Paragraphs_test.go
- vale/config/scripts/SmartQuotes_test.go
- vale/config/scripts/tengo.go
They are almost never semantically correct: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-br-element
> Error on <br> tags in source files

- .github/workflows/deploy-pr-preview.yml
> Don't run on forks

- .vale.ini
- vale/.vale.ini
> Only warn in CI and ignore bold tokens

- docs/sources/whats-new.md
- docs/sources/write/front-matter/index.md
Closes https://github.com/grafana/website/issues/23335
> Update release life cycle stage labels

- docs/sources/write/front-matter/index.md
https://deploy-preview-writers-toolkit-989-zb444pucvq-vp.a.run.app/docs/writers-toolkit/write/front-matter/#labels
> Clarify the different types of labels values

- docs/sources/review/lint-prose/rules.md
- vale/Grafana/styles/config/dictionaries/en_US-grafana.dic
- vale/dictionary/a.jsonnet
> Add anonymize and its finite forms to the dictionary

- docs/sources/write/style-guide/ux-writing/index.md
Added an example under the sentence case section.
Added a new section regarding product names from other companies.
See the following Slack conversation for context:
https://raintank-corp.slack.com/archives/C01EK60DKC5/p1737729651605899
- [ x] I've used a relevant pull request (PR) title.
- [ x] I've added a link to any relevant issues in the PR description.
> Added sentence case example and added product name guidance

- vale/Grafana/styles/config/dictionaries/en_US-grafana.dic
- vale/dictionary/d.jsonnet
Fixes failing Vale CI check in https://github.com/grafana/grafana/pull/96877
> Add 'passwordless' to dictionary

- docs/sources/write/front-matter/index.md
> Incorporate guidance from SEO presentation

- vale/Grafana/styles/config/dictionaries/en_US-grafana.dic
- vale/dictionary/i.jsonnet
- vale/dictionary/s.jsonnet
Closes https://github.com/grafana/writers-toolkit/issues/1033
Closes https://github.com/grafana/writers-toolkit/issues/1030
> Add inode and syntaxes to dictionary

- docs/sources/write/image-guidelines/index.md
Remove old note that actually doesn't make sense since repository assets could still be referenced by their published URL.
> Add note about upload size

- .github/workflows/validate-documentation.yml
- docs/sources/contribute/_index.md
- scripts/readability
Vale 3 introduced a new directory structure that broke this configuration.
It was broken because it couldn't find the dictionary file.
Vale 3 also introduced filters which is a much easier way to achieve the same thing.
> Fix readability script

- .github/workflows/dictionaries.yml
- prettier/action.yml
- vale/Grafana/styles/config/dictionaries/en_US-grafana.dic
- vale/Makefile
- vale/dictionary/c.jsonnet
Need to add this word for Grafana [PR 101021](https://github.com/grafana/grafana/pull/101021)
> Docs: Add cron to dictionary

- docs/sources/review/lint-prose/dictionary/_index.md
> fix: Update incorrect link in Grafana Labs’ dictionary doc.

- docs/sources/whats-new.md
- docs/sources/write/image-guidelines/index.md
Add information about how to take screenshots that will look good on high resolution screens.
**Please don't merge this until @robbymilo has reviewed.**
> Docs: Update screenshot guidelines

- docs/sources/review/lint-prose/rules.md
- vale/Grafana/styles/config/dictionaries/en_US-grafana.dic
- vale/dictionary/s.jsonnet
Also regenerate Vale rules.
Closes #1099
> Add subchart to dictionary

- docs/sources/write/style-guide/ux-writing/index.md
- vale-action/action.yml
> Properly pass through the changed files

- vale/Grafana/styles/Grafana/Headings.yml
- vale/Grafana/styles/Grafana/ProductPossessives.yml
- vale/Grafana/styles/Grafana/WordList.yml
- vale/Grafana/styles/config/dictionaries/en_US-grafana.dic
- vale/dictionary/j.jsonnet
Add `JMESPath` to the wordlist.
Relates to https://github.com/grafana/grafana/pull/101584
> Wordlist: Add JMESPath to the wordlist

- .vale.ini
- docs/sources/contribute/release-notes/index.md
- docs/sources/structure/topic-types/section/index.md
- docs/sources/structure/topic-types/tutorial/index.md
- docs/sources/write/image-guidelines/index.md
- docs/sources/write/shortcodes/index.md
- docs/sources/write/style-guide/style-conventions/index.md
- docs/sources/write/style-guide/ux-writing/index.md
- docs/sources/write/style-guide/voice-tone-guidelines/index.md
- docs/sources/write/style-guide/word-list/index.md
- docs/sources/write/style-guide/write-for-developers/index.md
- docs/sources/write/tooling-and-workflows/index.md
- vale/Grafana/styles/Grafana/CommandLinePrompts.yml
- vale/Grafana/styles/Grafana/Simple.yml
Define that we avoid the use of simple and easy as they are too subjective to be of value.
> Add easy and simple to word list

- vale/Grafana/styles/Grafana/Simple.yml
- vale/sarif.tmpl
- vale/tools/cmd/filter-sarif/filter.go
- vale/tools/cmd/filter-sarif/filter_test.go
- vale/tools/cmd/filter-sarif/main.go
- vale/tools/cmd/filter-sarif/sarif/sarif.go
> Inhibit rules based upon precedence levels

- docs/sources/write/shortcodes/index.md
Closes https://github.com/grafana/website/issues/23030.
> Document `anchorize` shortcode

- docs/sources/write/shortcodes/index.md
for https://github.com/grafana/website/issues/20551
see https://deploy-preview-writers-toolkit-1143-zb444pucvq-vp.a.run.app/docs/writers-toolkit/write/shortcodes/#figure
> replace figure shortcode relref

- docs/sources/write/shortcodes/index.md
Used in learning journeys for sharing content.
> Document `shared-snippet` shortcode

- publish-technical-documentation/action.yml
> Expose website_branch input for controlling the website repository branch

- .github/workflows/validate-documentation.yml
- build-website/action.yml
- vale-action/action.yml
> Add step that checks for binary assets

- .github/renovate-config.json5
- .github/workflows/validate-documentation.yml
Should prevent PRs like:
- https://github.com/grafana/writers-toolkit/pull/1126
- https://github.com/grafana/writers-toolkit/pull/1125
- https://github.com/grafana/writers-toolkit/pull/964
> Add package rules to skip annoying PRs

- docs/sources/write/image-guidelines/index.md
This PR includes a sentence to exclude elements from screenshots that are likely to change, such as the sidebar.
> Expand "Screenshot guidelines"

- docs/sources/write/shortcodes/index.md
Document the shortcode that @mdcruz created for learning journeys.
> docs: Add learning journey shortcode

- vale/Grafana/styles/Grafana/Headings.yml
- vale/Grafana/styles/Grafana/ProductPossessives.yml
- vale/Grafana/styles/Grafana/WordList.yml
- vale/Grafana/styles/config/dictionaries/en_US-grafana.dic
- vale/dictionary/y.jsonnet
Adding Yugabyte to the dictionary to fix the failure in grafana/website#26316
> Add Yugabyte to dictionary

- .github/instructions/writers-toolkit.instructions.md
I started revising the instructions and then stopped after spellchecking.
For the purposes of discussion and knowledge sharing, I'll revise this instructions in the PR as a review.
Relates to https://github.com/grafana/writers-toolkit/issues/1189
> Add Copilot instructions

- docs/sources/write/links/useful-link-text.md
Tries to answer the question of whether to use
Example 1: Refer to the [tail_sampling processor]() documentation
OR
Example 2: Refer to the [tail_sampling processor documentation]()
> Add general guidance for what words to include in the link text

- .github/instructions/writers-toolkit.instructions.md
> Update writers-toolkit.instructions full stop example

- docs/sources/review/lint-prose/rules.md
- docs/sources/write/shortcodes/index.md
> Fix broken links

- docs/sources/structure/_index.md
It currently has broken HTML which causes the page to break (https://grafana.com/docs/writers-toolkit/structure/):
> fix table on structure page

- docs/sources/write/links/_index.md
Also add a caution that more clearly explains the need for front matter when linking between versioned projects.
Closes https://github.com/grafana/writers-toolkit/issues/1208
> Clarify the decision making process for version substitution
